# Generated by Django 4.2.5 on 2023-09-22 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_schedule_generated', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='is_rest_day',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.venue'),
        ),
    ]
