# Generated by Django 4.2.5 on 2023-09-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_scheduleflag_remove_schedule_is_rest_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='goals',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
