# Generated by Django 4.2.5 on 2023-09-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_match_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1_goals',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='team2_goals',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
