# Generated by Django 4.2.5 on 2023-09-23 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_match_team1_goals_match_team2_goals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='goals',
        ),
    ]
