# Generated by Django 4.2.5 on 2023-09-23 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_remove_match_goals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='venue',
        ),
        migrations.DeleteModel(
            name='ScheduleFlag',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
